//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adjustment_course_design.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adjustment_course_design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1,0,0
        ///0,1,0
        ///1,0,0
        ///0,1,0
        ///-1,1,0
        ///-1,0,1
        ///0,0,-1 的本地化字符串。
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号,测段距离,高差观测值,端点号
        ///1,1.1,1.359,1-3
        ///2,1.7,2.009,1-4
        ///3,2.3,0.363,2-3
        ///4,2.7,1.012,2-4
        ///5,2.4,0.657,3-4
        ///6,1.4,0.238,3-5
        ///7,2.6,-0.595,5-2
        ///5.016,6.016 的本地化字符串。
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 n = 7, t = 3, r = n - t = 4, c = 7
        ///H1 = 5.016, H2 = 6.016
        ///
        ///X1 = H3, X2 = H4, X3 = H5;
        ///
        ///L^ = Li + vi
        ///
        /////观测值方程
        ///L1 + V1 = X1 - H1;
        ///L2 + V2 = X2 - H1;
        ///L3 + V3 = X1 - H2;
        ///L4 + V4 = X2 - H2;
        ///L5 + V5 = X2 - X1;
        ///L6 + V6 = X3 - X1;
        ///L7 + V7 = H2 - X3;
        ///
        /////误差方程
        ///V1 = X1 - H1 - L1;
        ///V2 = X2 - H1 - L2;
        ///V3 = X1 - H2 - L3;
        ///V4 = X2 - H2 - L4;
        ///V5 = X2 - X1 - L5;
        ///V6 = X3 - X1 - L6;
        ///V7 = H2 - X3 - L7;
        ///
        /////法方程
        ///Bx - l  = 0
        ///
        ///B				X		  l
        ///1	0	0				6.375
        ///0	1	0				7.025
        ///1	0	0		X1		6.379
        ///0	1	0	*	X2	-	7.028 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string equation {
            get {
                return ResourceManager.GetString("equation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 6.375
        ///7.025
        ///6.379
        ///7.028
        ///0.657
        ///0.238
        ///-6.611 的本地化字符串。
        /// </summary>
        internal static string l {
            get {
                return ResourceManager.GetString("l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Open_file {
            get {
                object obj = ResourceManager.GetObject("Open_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
